"""
Manages Twitch Miner subprocess lifecycles.

Each miner instance runs as a separate Python subprocess with its own:
  - run.py (generated config)
  - cookies/ folder (persisted across restarts)
  - logs/ folder (tailed for WebSocket streaming)
"""

import asyncio
import os
import signal
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path

from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.models.database import MinerInstance, async_session
from app.models.enums import InstanceState

logger = logging.getLogger(__name__)



class MinerProcessManager:
    """Singleton that tracks all running miner subprocesses."""

    async def cleanup_orphan_processes(self):
        """
        Entfernt verwaiste Prozesse aus dem Tracking, die nicht mehr laufen.
        """
        to_remove = []
        for instance_id, proc in self._processes.items():
            if proc.returncode is not None:
                to_remove.append(instance_id)
            else:
                # Prüfe, ob der Prozess noch existiert
                try:
                    os.kill(proc.pid, 0)
                except OSError:
                    to_remove.append(instance_id)
        for instance_id in to_remove:
            logger.info(f"Entferne verwaisten Prozess aus Tracking: {instance_id}")
            self._processes.pop(instance_id, None)
            self._pipe_tasks.pop(instance_id, None)
            self._stopped_by_request.discard(instance_id)

    def __init__(self):
        # instance_id -> asyncio.subprocess.Process
        self._processes: dict[str, asyncio.subprocess.Process] = {}
        # instance_id -> asyncio.Task for _pipe_output
        self._pipe_tasks: dict[str, asyncio.Task] = {}
        # Tracks which instances were stopped explicitly (to avoid race with _pipe_output)
        self._stopped_by_request: set[str] = set()

    # ------------------------------------------------------------------
    # Generate run.py for a miner instance
    # ------------------------------------------------------------------
    def _generate_run_script(
        self,
        instance_dir: Path,
        twitch_username: str,
        streamers: list[str],
    ) -> Path:
        """Create a run.py based on the official example.py with sensible defaults."""
        streamer_lines = "\n".join(f'        "{s}",' for s in streamers)

        # Add MINER_REPO_PATH to sys.path if configured
        miner_repo_path = settings.MINER_REPO_PATH
        sys_path_insert = ""
        if miner_repo_path:
            # Expand ~ to home directory
            expanded_path = str(Path(miner_repo_path).expanduser())
            sys_path_insert = (
                f'import sys\n'
                f'sys.path.insert(0, "{expanded_path}")\n\n'
            )

        script = (
            "# -*- coding: utf-8 -*-\n"
            "# Auto-generated by Twitch Miner Backend\n"
            "\n"
            f"{sys_path_insert}"
            "import logging\n"
            "from colorama import Fore\n"
            "from TwitchChannelPointsMiner import TwitchChannelPointsMiner\n"
            "from TwitchChannelPointsMiner.logger import LoggerSettings, ColorPalette\n"
            "from TwitchChannelPointsMiner.classes.Chat import ChatPresence\n"
            "from TwitchChannelPointsMiner.classes.Settings import Priority, Events, FollowersOrder\n"
            "from TwitchChannelPointsMiner.classes.entities.Bet import Strategy, BetSettings, Condition, OutcomeKeys, FilterCondition, DelayMode\n"
            "from TwitchChannelPointsMiner.classes.entities.Streamer import Streamer, StreamerSettings\n"
            "\n"
            "twitch_miner = TwitchChannelPointsMiner(\n"
            f'    username="{twitch_username}",\n'
            "    claim_drops_startup=True,\n"
            "    priority=[\n"
            "        Priority.STREAK,\n"
            "        Priority.DROPS,\n"
            "        Priority.ORDER,\n"
            "    ],\n"
            "    enable_analytics=False,\n"
            "    disable_ssl_cert_verification=False,\n"
            "    logger_settings=LoggerSettings(\n"
            "        save=True,\n"
            "        console_level=logging.INFO,\n"
            "        console_username=False,\n"
            "        auto_clear=True,\n"
            "        file_level=logging.INFO,\n"
            "        emoji=True,\n"
            "        less=False,\n"
            "        colored=False,\n"
            "        color_palette=ColorPalette(\n"
            '            STREAMER_online="GREEN",\n'
            '            streamer_offline="red",\n'
            "            BET_wiN=Fore.MAGENTA,\n"
            "        ),\n"
            "    ),\n"
            "    streamer_settings=StreamerSettings(\n"
            "        make_predictions=True,\n"
            "        follow_raid=True,\n"
            "        claim_drops=True,\n"
            "        claim_moments=True,\n"
            "        watch_streak=True,\n"
            "        community_goals=False,\n"
            "        chat=ChatPresence.ONLINE,\n"
            "        bet=BetSettings(\n"
            "            strategy=Strategy.SMART,\n"
            "            percentage=5,\n"
            "            percentage_gap=20,\n"
            "            max_points=50000,\n"
            "            stealth_mode=True,\n"
            "            delay_mode=DelayMode.FROM_END,\n"
            "            delay=6,\n"
            "            minimum_points=20000,\n"
            "            filter_condition=FilterCondition(\n"
            "                by=OutcomeKeys.TOTAL_USERS,\n"
            "                where=Condition.LTE,\n"
            "                value=800,\n"
            "            ),\n"
            "        ),\n"
            "    ),\n"
            ")\n"
            "\n"
            "twitch_miner.mine(\n"
            "    [\n"
            f"{streamer_lines}\n"
            "    ],\n"
            "    followers=False,\n"
            "    followers_order=FollowersOrder.ASC,\n"
            ")\n"
        )

        run_path = instance_dir / "run.py"
        run_path.write_text(script)
        return run_path

    # ------------------------------------------------------------------
    # Instance directory setup
    # ------------------------------------------------------------------
    def _ensure_instance_dir(self, instance_id: str) -> Path:
        """Create and return the instance's data directory."""
        instance_dir = settings.INSTANCES_DIR / instance_id
        (instance_dir / "cookies").mkdir(parents=True, exist_ok=True)
        (instance_dir / "logs").mkdir(parents=True, exist_ok=True)
        (instance_dir / "analytics").mkdir(parents=True, exist_ok=True)
        return instance_dir

    # ------------------------------------------------------------------
    # Kill process tree
    # ------------------------------------------------------------------
    @staticmethod
    def _kill_process_tree(pid: int) -> None:
        """Kill a process and all its children via SIGKILL to the process group."""
        try:
            os.killpg(os.getpgid(pid), signal.SIGKILL)
        except (ProcessLookupError, PermissionError, OSError) as e:
            logger.debug(f"Process tree kill for PID {pid}: {e}")

    # ------------------------------------------------------------------
    # Start a miner
    # ------------------------------------------------------------------
    async def start(
        self,
        instance_id: str,
        twitch_username: str,
        streamers: list[str],
    ) -> int:
        """
        Start the miner subprocess. Returns the OS PID.
        Raises RuntimeError if already running.
        """
        if instance_id in self._processes:
            proc = self._processes[instance_id]
            if proc.returncode is None:
                raise RuntimeError(f"Instance {instance_id} is already running (PID {proc.pid})")

        instance_dir = self._ensure_instance_dir(instance_id)
        run_script = self._generate_run_script(
            instance_dir, twitch_username, streamers
        )

        # Start subprocess in the instance's directory
        # The miner writes cookies/logs relative to cwd
        # Set PYTHONIOENCODING to UTF-8 to handle emoji output on Windows
        # Use sys.executable to ensure we use the same Python interpreter (from venv)
        env = {**os.environ, "PYTHONUNBUFFERED": "1", "PYTHONIOENCODING": "utf-8"}

        # Use start_new_session so we can kill the entire process group via killpg
        kwargs = {"start_new_session": True}

        process = await asyncio.create_subprocess_exec(
            sys.executable, str(run_script),
            cwd=str(instance_dir),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
            env=env,
            **kwargs,
        )

        self._processes[instance_id] = process
        self._stopped_by_request.discard(instance_id)
        logger.info(f"Started miner instance {instance_id} with PID {process.pid}")

        # Pipe stdout to a combined log file (tracked so stop() can await completion)
        task = asyncio.create_task(self._pipe_output(instance_id, instance_dir, process))
        self._pipe_tasks[instance_id] = task

        # Update DB
        async with async_session() as db:
            result = await db.execute(
                select(MinerInstance).where(MinerInstance.id == instance_id)
            )
            inst = result.scalar_one_or_none()
            if inst:
                inst.status = InstanceState.RUNNING
                inst.pid = process.pid
                inst.last_started_at = datetime.now(timezone.utc)
                await db.commit()

        return process.pid

    # ------------------------------------------------------------------
    # Pipe subprocess output to log file
    # ------------------------------------------------------------------
    async def _pipe_output(
        self,
        instance_id: str,
        instance_dir: Path,
        process: asyncio.subprocess.Process,
    ):
        """Read stdout line by line and write to a combined log file."""
        log_file = instance_dir / "logs" / "output.log"
        try:
            with open(log_file, "a", encoding="utf-8") as f:
                async for line in process.stdout:
                    decoded = line.decode("utf-8", errors="replace")
                    f.write(decoded)
                    f.flush()
        except Exception as e:
            logger.error(f"Error piping output for {instance_id}: {e}")
        finally:
            await process.wait()
            logger.info(f"Miner instance {instance_id} exited with code {process.returncode}")
            self._processes.pop(instance_id, None)
            self._pipe_tasks.pop(instance_id, None)

            # Only update DB if stop() didn't already handle it
            if instance_id in self._stopped_by_request:
                self._stopped_by_request.discard(instance_id)
                return

            async with async_session() as db:
                result = await db.execute(
                    select(MinerInstance).where(MinerInstance.id == instance_id)
                )
                inst = result.scalar_one_or_none()
                if inst:
                    inst.status = InstanceState.STOPPED
                    inst.pid = None
                    inst.last_stopped_at = datetime.now(timezone.utc)
                    await db.commit()

    # ------------------------------------------------------------------
    # Stop a miner
    # ------------------------------------------------------------------
    async def stop(self, instance_id: str) -> bool:
        """
        Gracefully stop a miner and wait until the process has fully exited.

        1. Sets DB status to STOPPING immediately (so other requests see it).
        2. Sends SIGTERM to let the miner close WebSocket / IRC cleanly.
        3. Falls back to force-kill after *GRACEFUL_TIMEOUT* seconds.
        4. Sets DB status to STOPPED before returning.

        The caller (stop endpoint) blocks until this method returns,
        so the frontend receives the response only when shutdown is complete.

        Returns True if stopped, False if wasn't running.
        """
        GRACEFUL_TIMEOUT = 30  # seconds to wait for graceful shutdown
        FORCE_TIMEOUT = 10    # seconds to wait after force-kill

        proc = self._processes.get(instance_id)
        if proc is None or proc.returncode is not None:
            # Clean up stale entry
            self._processes.pop(instance_id, None)
            return False

        pid = proc.pid
        logger.info(f"Stopping miner instance {instance_id} (PID {pid})")

        # Mark as stopped by request so _pipe_output skips DB update
        self._stopped_by_request.add(instance_id)

        # --- 0. Set STOPPING in DB immediately --------------------------
        async with async_session() as db:
            result = await db.execute(
                select(MinerInstance).where(MinerInstance.id == instance_id)
            )
            inst = result.scalar_one_or_none()
            if inst:
                inst.status = InstanceState.STOPPING
                await db.commit()

        # --- 1. Graceful SIGTERM to the process group -------------------
        try:
            os.killpg(os.getpgid(pid), signal.SIGTERM)
        except (ProcessLookupError, PermissionError, OSError) as e:
            logger.debug(f"Graceful signal for PID {pid}: {e}")

        # --- 2. Wait for graceful exit ----------------------------------
        try:
            await asyncio.wait_for(proc.wait(), timeout=GRACEFUL_TIMEOUT)
            logger.info(
                f"Instance {instance_id} (PID {pid}) exited gracefully "
                f"with code {proc.returncode}"
            )
        except asyncio.TimeoutError:
            # --- 3. Force-kill -------------------------------------------
            logger.warning(
                f"Graceful stop timed out after {GRACEFUL_TIMEOUT}s for "
                f"instance {instance_id} (PID {pid}), force-killing"
            )
            self._kill_process_tree(pid)
            try:
                await asyncio.wait_for(proc.wait(), timeout=FORCE_TIMEOUT)
            except asyncio.TimeoutError:
                logger.warning(f"Force-killing main process {pid}")
                try:
                    proc.kill()
                except ProcessLookupError:
                    pass
                await proc.wait()

        # --- 4. Wait for _pipe_output task to finish --------------------
        pipe_task = self._pipe_tasks.get(instance_id)
        if pipe_task and not pipe_task.done():
            try:
                await asyncio.wait_for(pipe_task, timeout=5)
            except (asyncio.TimeoutError, asyncio.CancelledError):
                pipe_task.cancel()

        self._processes.pop(instance_id, None)
        self._pipe_tasks.pop(instance_id, None)

        # --- 5. Set STOPPED in DB ---------------------------------------
        async with async_session() as db:
            result = await db.execute(
                select(MinerInstance).where(MinerInstance.id == instance_id)
            )
            inst = result.scalar_one_or_none()
            if inst:
                inst.status = InstanceState.STOPPED
                inst.pid = None
                inst.last_stopped_at = datetime.now(timezone.utc)
                await db.commit()

        return True

    # ------------------------------------------------------------------
    # Status check (in-memory only, used for start/stop guards)
    # ------------------------------------------------------------------
    def is_process_tracked(self, instance_id: str) -> bool:
        """Check if we have a live process object for this instance."""
        proc = self._processes.get(instance_id)
        return proc is not None and proc.returncode is None

    def get_pid(self, instance_id: str) -> int | None:
        proc = self._processes.get(instance_id)
        if proc and proc.returncode is None:
            return proc.pid
        return None

    # ------------------------------------------------------------------
    # Startup: reset all DB flags to false
    # ------------------------------------------------------------------
    @staticmethod
    async def reset_all_on_startup():
        """Reset all instances to STOPPED on API startup."""
        async with async_session() as db:
            result = await db.execute(
                update(MinerInstance)
                .where(MinerInstance.status != InstanceState.STOPPED)
                .values(status=InstanceState.STOPPED, pid=None)
            )
            if result.rowcount > 0:
                logger.info(f"Reset {result.rowcount} instance(s) to STOPPED on startup")
            await db.commit()

    # ------------------------------------------------------------------
    # Cleanup on shutdown
    # ------------------------------------------------------------------
    async def shutdown_all(self):
        """Stop all running miners (called on app shutdown)."""
        for instance_id in list(self._processes.keys()):
            await self.stop(instance_id)


# Global singleton
miner_manager = MinerProcessManager()
